### ISSUE TITLE
can't set breakpoints in VSCode 1.28.2

### ISSUE THREAD

**Issue by davydden** [paulo-fernando-silva/vscOctaveDebugger#16]
I can't set breakpoints in VSCode 1.28.2 and macOS Mojave 10.14.1.

@PeterEnis1234 writes in [original issue](https://github.com/paulo-fernando-silva/vscOctaveDebugger/issues/9)

> Same problem on Windows

so it looks like it's not OS specific.

simple `gif` to demonstrate it on a project with 2 files:
```
/c++
/c++/hallo.c
/octave
/octave/hallo.m
```

![octave_breakpoints](https://user-images.githubusercontent.com/8023934/48055689-194c8280-e1a8-11e8-8658-76ddd7d3ae18.gif)

**Comment by paulo-fernando-silva** [comment]
Hm, in my case it works. I have a similar project, and I can place breakpoints on both. Can you set "trace": true in your launch.json and let me post the output here?

**Comment by paulo-fernando-silva** [comment]
I think I know the issue. Your language is set to Octave, while the plugin expects it to be MATLAB. Can you change and test?
Say, add
"files.associations": {"*.m": "matlab"},
to your settings.json.

**Comment by davydden** [comment]
> the plugin expects it to be MATLAB.

I have [Octave](https://marketplace.visualstudio.com/items?itemName=toasty-technologies.octave) plugin installed which adds syntax highlighting for `octave`. 

Is this a limitation from VSCode that you need to support only one type of association (i.e. `MATLAB` file or `Octave`)? If not, I would suggest to support both. From user perspective, it's quite confusing that `octave` debugger plugin needs `.m` files to be associated with Matlab.

> Can you change and test?

If I install [Matlab](https://marketplace.visualstudio.com/items?itemName=Gimly81.matlab) language support plugin, then the debugger works indeed.

Presumably that's what you use. But this should certainly be documented because without any extra plugin VSCode won't be able to associate `.m` with neither Octave nor Matlab.

**Comment by paulo-fernando-silva** [comment]
The issue is that I didn't even know there was an octave language extension I believe.
Besides the matlab extension has cuter icons. Nevertheless I modified the package.json to add matlab and octave language support even without the extensions. But I do suggest them in the readme now.

This is fixed in v0.2.4. Test it and let me know if we can close this issue.

**Comment by davydden** [comment]
@paulo-fernando-silva 

> This is fixed in v0.2.4. Test it and let me know if we can close this issue.

thanks a lot, really appreciate it!  👍 

My VSCode has not realized yet that there was an update, so I will test ASAP, but for now closing this issue.
