### ISSUE TITLE
Why two stack requests?

### ISSUE THREAD

**Issue by paulo-fernando-silva** [paulo-fernando-silva/vscOctaveDebugger#2]
Not sure if this is a bug or if it's working as expected. But it seems that stack calls always come in pairs and they ask for the same thing.

**Comment by paulo-fernando-silva** [comment]
Apparently it's supposed to be more or less that way.

**Comment by theIDinside** [comment]
This is still currently an issue. It sends 2 stackTraceRequest, and it does not request the first stackframe and then 19, as previously explained in bug mentioned above. It sends two, with levels set to 20 both times.

**Comment by paulo-fernando-silva** [comment]
Hello Simon.
I didn't really look into it any further. It's weird, but I think that's
about it.
So far no one complained about anything related to it. Is it causing you
some issues?
If so you could post a bug with repro steps.
Thanks
Paulo
