### ISSUE TITLE
command not found: octave-cli

### ISSUE THREAD

**Issue by shaunenslin** [paulo-fernando-silva/vscOctaveDebugger#22]
Hi
I am running the debugger on a mac with high sierra.
I installed octave 4.4.1 via the app dmg installer from the web site.
In my app folder, I have
Octave-4.4.1.app
Octave-cli.app
Octave-gui.app

When I run debug, I get the above error. 
Any thoughts on where I went wrong?

**Comment by paulo-fernando-silva** [comment]
Hi!
It's likely that you don't have the octave-cli in your PATH. But that's not essential. In your launch.json you can set it using "octave": "octave-cli", for example
        {
            "type": "OctaveDebugger",
            "request": "launch",
            "name": "foo",
            "program": "bar",
            "octave": "/path/to/Octave-cli.app/Contents/MacOS/octave-cli",
        }
Something like that should work. hm, I guess I don't really have an explanation for that in the readme. I shall add one.
Let me know if that helps.

**Comment by paulo-fernando-silva** [comment]
I'm closing this as I guess it fixed the issue. Open it again if that's not the case.
