### ISSUE TITLE
Slash in string as function argument in debug configuration leads to syntax error

### ISSUE THREAD

**Issue by Braendle** [paulo-fernando-silva/vscOctaveDebugger#25]
Using a front slash in a function argument in "program" in the Debug Session Configuration leads to an internal syntax error:

For example:
```
...
"program": "test_function(\"test/test\")",
...
```

**Comment by paulo-fernando-silva** [comment]
Hi Braendle, thanks for reporting this issue.
I've published version v0.3.15 which fixes this issue. I'll close the bug now, but feel free to reopen it in case the fix doesn't work for you.
Thanks
