### ISSUE TITLE
Name-check Octave Hacking?

### ISSUE THREAD

**Issue by apjanke** [paulo-fernando-silva/vscOctaveDebugger#29]
Hi Paulo,

I see that in your README you're recommending other Octave VS Code extensions for syntax highlighting and the like. Would you consider checking out [my Octave Hacking extension](https://marketplace.visualstudio.com/items?itemName=apjanke.octave-hacking) and maybe including that in the list of recommendations?

Octave Hacking improves on the other Octave language support extensions in the VS Code Marketplace by:
* adding Outline View navigation support
* doing some customizations and improvements on the syntax definition beyond what the original TextMate language bundle provides (which is what the other extensions seem to be using, unmodified), and 
* providing some snippets for common code structures

Cheers, and thank you for writing this extension!

Andrew Janke

**Comment by paulo-fernando-silva** [comment]
Sure. I've been quite busy, but allow me a bit of time to take a look. Thanks.

**Comment by paulo-fernando-silva** [comment]
I like the outline navigation. It would be nice to have also a F12 or "jump to definition" functionality. Didn't look into what is needed for that though. Thanks!

**Comment by apjanke** [comment]
My plan is to add All That! I am looking in to writing a VS Code Language Server component for Octave which will allow more sophisticated processing of the source code and building up symbol tables, which will support Jump To Definition, a nicer Outline view, and more.

Don't hold your breath, though. This will be a large project, much bigger than the basic regex-based stuff the base language support is doing.
