### ISSUE TITLE
local variables does not show dimensions?

### ISSUE THREAD

**Issue by TaiPhamD** [paulo-fernando-silva/vscOctaveDebugger#32]
I remember when I first started using this a few days the local variable shows the dimensions but now it doesn't . 

<img width="355" alt="Screen Shot 2020-04-18 at 12 18 37 AM" src="https://user-images.githubusercontent.com/10516699/79630918-280fc680-810a-11ea-837b-988c4c3e5d87.png">

Any idea how i can get the local variables to show the dimensions?

**Comment by paulo-fernando-silva** [comment]
Hi TaiPhamD, can you post some sample code that leads to this behavior?
Thanks

**Comment by TaiPhamD** [comment]
I created a simple test .m script and the dimensions appear to be working correctly. The code that has this problem is ex5.m (Week 6 hw) from Andrew Ng's ML learning class on Coursera. I am don't think I can post that HW code online since I think coursera has the copy right on that. Let me try to see what's different about that code that's causing this issue and maybe I can post it. Alternatively, since this course is free from coursera perhaps you can jump directly to week6 and download the hw.zip?

**Comment by TaiPhamD** [comment]
ahh it seems to break when you load the matrix from a .mat file? When I declare the variables locally it is fine but after i load a .mat file it has problems. 

<img width="822" alt="Screen Shot 2020-04-18 at 12 37 05 AM" src="https://user-images.githubusercontent.com/10516699/79631244-c9981780-810c-11ea-8593-2c46f78ca51b.png">
<img width="687" alt="Screen Shot 2020-04-18 at 12 37 13 AM" src="https://user-images.githubusercontent.com/10516699/79631248-cac94480-810c-11ea-963c-7109618f792b.png">

**Comment by paulo-fernando-silva** [comment]
ic. There's a couple of things going on here. First the matrix size is only shown when the number of elements is large - which is the same as saying 100 elements times `prefetchCount`, or 100 by default. The variables loaded from the .mat file are less than 100 elements so the value of each element will be shown instead. However, since these are column nx1 vectors the you only see the first element of the vector. To see the entire column you have to hover with the mouse. I implemented it like that as that's how octave would display them. But I guess I could display column and row vectors in the same way... Will have to think about it. 🤔

**Comment by paulo-fernando-silva** [comment]
It's also possible that it's preferable to show the size instead of the value. I guess I can add a switch to the launch configuration to support that. How does it sound?

**Comment by TaiPhamD** [comment]
I think that would be a great feature to add I as an option to always show dimension . While working in these code it’s very helpful for me to quickly know if the variable is a row or column vector or if it’s a matrix. I’ve been manually typing size in the debugger to get this info.

Also, thank you very much for making this plugin . I use octave on macos and the QT GUI is so buggy on macos (probably other Os too) so having this tool in visual studio code has been great to work with !

**Comment by paulo-fernando-silva** [comment]
Thanks. I'm glad the plugin is useful. 😃

I was thinking about it and remembered that you can always check the size and type of the variable if you move the mouse over the variable name. Did you try that? Would that be enough?

**Comment by TaiPhamD** [comment]
yes I tried the hover feature (didn't know it existed) and it's a lot more convenient than me typing size() to check. This is good enough for me. Thank you!

**Comment by paulo-fernando-silva** [comment]
Great. Thanks.
