### ISSUE TITLE
remove_all_breakpoint_in_file: unable to find function ex1

### ISSUE THREAD

**Issue by slysenko** [paulo-fernando-silva/vscOctaveDebugger#33]
Hello,

1. I have Andrew Ng's course files on my Mac:
`~/Projects/HOME/Learn ML AndrewNg/machine-learning-ex1/ex1
`
my `${workspaceFolder}` is `~/Projects/HOME/Learn ML AndrewNg
`
2. I open `ex1.m` file
3. Create config as follows:
```
"configurations": [
        {
            "type": "OctaveDebugger",
            "request": "launch",
            "name": "Function or file to execute.",
            "program": "${file}",
            "octave": "octave-cli",
            "sourceFolder": "${workspaceFolder}",
            "autoTerminate": true
        }
    ]
```
4. Set breakpoint at line 33 which is warmUpExercise()
5. press the Run button
6. Get the error message in the debug console:
error: remove_all_breakpoint_in_file: unable to find function ex1
Runtime: octave-cli exited with code: 1

If I follow the same steps WITHOUT setting a breakpoint, the ex1 file runs fine

**Comment by paulo-fernando-silva** [comment]
Hi Sergey, I'll have to take a look. In the meanwhile if your workspace is the directory ex1 it should work.

Can you also add a `"verbose": true` to your launch.json and attach the output from the debug console here? Thanks.

**Comment by slysenko** [comment]
`To client: {"seq":0,"type":"response","request_seq":1,"command":"initialize","success":true,"body":{"supportsConfigurationDoneRequest":true,"supportsEvaluateForHovers":true,"supportsConditionalBreakpoints":true,"supportsHitConditionalBreakpoints":true,"supportsSetVariable":true,"supportsStepBack":false,"supportTerminateDebuggee":true}}
`

**Comment by paulo-fernando-silva** [comment]
Hi, check version v0.4.3, it fixes this issue.
Please reopen the bug If it doesn't work for you.

As a note, you have to press enter in the DEBUG CONSOLE when ex1 outputs 'Program paused. Press enter to continue.", even though the UI is showing the graphs in the background.
