### ISSUE TITLE
Fails with quote in workspace path

### ISSUE THREAD

**Issue by nickmertin** [paulo-fernando-silva/vscOctaveDebugger#37]
Workspace paths with quotes, which are valid file paths, fail with error:

```
parse error:
  syntax error
>>> addpath('/path/with/quote/doesn't/work')

Runtime: octave-cli exited with code: 1
```

Note that I can use octave just fine running the `octave` command inside the directory in question.

**Comment by paulo-fernando-silva** [comment]
Hi, thanks for reporting this issue. I'll take a look very soon.

**Comment by paulo-fernando-silva** [comment]
Hey, sorry for the delay. Check the latest version v0.4.7 and reopen this issue if that doesn't fix it for you. Thanks!
