### ISSUE TITLE
error: No such file or directory on Windows 10

### ISSUE THREAD

**Issue by infinity-plus** [paulo-fernando-silva/vscOctaveDebugger#38]
**Extension Info:**
Name: Octave Debugger
Id: paulosilva.vsc-octave-debugger
Description: Debug Octave and Matlab code in Visual Studio Code.
Version: 0.4.7
Publisher: Paulo Silva
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=paulosilva.vsc-octave-debugger

**Octave Info:**
I have installed GNU Octave in `E:\Octave-6.1.0` directory. octave-cli resides in `E:\Octave-6.1.0\mingw64\bin`.
I wrote a simple Hello World Script and named it "myscript.m" inside my folder: `D:\Harsh\Study\Sem4\ITW-2`.

**Issue:**
Every time I run the script using the debugger, it gives a warning and an error in Debug Console, that is as follows:

```
warning: addpath: D:HarshStudySem4ITW-2: No such file or directory
error: D:HarshStudySem4ITW-2: No such file or directory
Runtime: octave-cli exited with code: 1
```
**Configuration:**
My launch.json is configured as:
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "OctaveDebugger",
            "request": "launch",
            "name": "Run Octave",
            "program": "${fileBasename}",
            "octave": "octave-cli",
            "sourceFolder": "${workspaceFolder}",
            "autoTerminate": true
        }
    ]
}
```

Clearly, backslashes from path are removed; `D:\Harsh\Study\Sem4\ITW-2` becomes `D:HarshStudySem4ITW-2`.

I need help regarding this. I am still very very new to octave. Please assist.

**Comment by infinity-plus** [comment]
I confirm octave is in my path and running `octave myscript.m` from command prompt works just fine.

**Comment by loisspitz** [comment]
I have the same problem on Windows 10. I tried the combinations `//`,  `\/`,  `/` and `\`. Just going back to version 0.4.6 helped.

**Comment by paulo-fernando-silva** [comment]
Sorry. I broke the plugin in the last commit. I didn't test it on windows. The new version v0.4.8 should be up at any moment and should fix this. Let me know if it works for you guys.

**Comment by loisspitz** [comment]
Perfekt! Works like expected!

**Comment by paulo-fernando-silva** [comment]
Great. I'll close the bug now. Thanks for posting.
