### ISSUE TITLE
Passing environment variables to octave

### ISSUE THREAD

**Issue by Braendle** [paulo-fernando-silva/vscOctaveDebugger#49]
Hi,
until e37c0ee50a30f87e0a5aa656dd8b8c6b750a32e1 I could pass environment variables by prepending the "octave" setting with e.g. `export DISPLAY=:22; octave`.
With `shell` not set to `true` this doesn't work anymore.

Is there any other way to pass environment variables to octave? I couldn't find a working solution.

**Comment by paulo-fernando-silva** [comment]
I seez. hmm... I can't remember why I added that. I think I'll remove it because I don't think it's doing anything.

**Comment by paulo-fernando-silva** [comment]
Just published version 0.4.15 which adds support for environment variables and more. Both the method you described and `"octaveEnvironment": { "FOO": "bar", "VAR": "XPTO" },` are supported. Check readme for details.
