### ISSUE TITLE
'octave-cli' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by mustaqimadha** [paulo-fernando-silva/vscOctaveDebugger#57]
I installed Octave 6.3.0 on my laptop which is running Windows 10. When I tried to debug my .m file, the sentence shown on the debug console.

![image](https://user-images.githubusercontent.com/80674326/135799146-bf4fff41-fce0-403e-b88c-56495204c2d3.png)

What must I do to make octave-cli or octave-gui to be recognized as an internal or external command? Or what is the problem that I am facing? How to fix the problem?

**Comment by paulo-fernando-silva** [comment]
Is octave-cli in you PATH? You can check that by trying to run either octave-gui or octave-cli from the command line, i.e. cmd.exe
If it's not in your PATH, then you can add it via the environment variables dialog.

I guess it would be nice if the plugin downloaded octave directly? Maybe we could get it running out of the box.

**Comment by mustaqimadha** [comment]
This is my PATH. I have added directory of octave-cli.exe.
![image](https://user-images.githubusercontent.com/80674326/136155954-ca2c9d28-b9ca-4341-bafd-f33a0b6244b8.png)

Then, the debug console shows the error message.
![image](https://user-images.githubusercontent.com/80674326/136156316-869da86c-01c1-43fb-8ace-9bb3ff998c44.png)

**Comment by paulo-fernando-silva** [comment]
Great. Congratulations. I hope you find it useful. I'll close this issue. :)
