### ISSUE TITLE
Plots close as soon as running the code, is there any way to stop this without adding lines at end of code

### ISSUE THREAD

**Issue by nikhilCad** [paulo-fernando-silva/vscOctaveDebugger#58]
Readme suggests
```
    h = figure();
    plot();
    % ...
    waitfor(h);
```

or ```while(waitforbuttonpress()==0) pause(1) end``` this

Is there any way the extension can make plots not close without adding any additional codes in the file?

**Comment by paulo-fernando-silva** [comment]
Closing. Please reopen if the problem persists.
