### ISSUE TITLE
Does not work with Octave Formatter extension on Vscode

### ISSUE THREAD

**Issue by ICHx** [paulo-fernando-silva/vscOctaveDebugger#59]
The problem is while this extension uses the 'octave' language, Octave formatter uses 'Octave'.  That made both extensions could only be used exclusively.

<img width="141" alt="圖片" src="https://user-images.githubusercontent.com/11556527/140440761-32d6c8ed-e6dc-4780-b93e-76c18e18eece.png">

https://marketplace.visualstudio.com/items?itemName=tusindfryd.octave-formatter

**Comment by paulo-fernando-silva** [comment]
Sorry. I don't use that extension. But I've added some language aliases. Maybe it'll work now. Test, and let me know if that works for you.

**Comment by paulo-fernando-silva** [comment]
Closing. Please reopen if the problem persists.
