### ISSUE TITLE
Question about compatibility of matlab debugging

### ISSUE THREAD

**Issue by pglira** [paulo-fernando-silva/vscOctaveDebugger#64]
Thank you for sharing this extension.

It seems that when I use matlab functions which do not exist in octave (e.g. a function from a matlab toolbox), the debugger issues an error. 

Is my assumption correct, that the extension can only be used for functions which exist in octave?

**Comment by paulo-fernando-silva** [comment]
Yes, the debugger plugin doesn't add any extra code to octave. You have to add the implementation of those functions to your source somewhere. For example, if those functions are implemented in some .m file, then you can add the file location to your code using `addpath()`. If they are part of matlab's binary then it's likely you have to use matlab to run them. Maybe there's some open source version of those functions that you can use.

The debugger shouldn't issue an error if the function is not found. That error comes from octave not from the swbuffwe plugin. Does that help?

I'm closing this now, but you can ask further questions on the thread.
