### ISSUE TITLE
Add `reload` to README.md

### ISSUE THREAD

**Issue by Its-Just-Nans** [paulo-fernando-silva/vscOctaveDebugger#65]
Hello,

Note that I needed to reload my VSCode to work.

Maybe it can be great to put it in the `README.md`

**Comment by paulo-fernando-silva** [comment]
Hi, restarting is not needed. Sometimes you might need to restart vscode when it installs a new version. But that is unrelated with this plugin. That's vscode general behavior. You should be able to install the plugin and run it immediately.

**Comment by Its-Just-Nans** [comment]
I think it was a bug related to vscode
